# -*- coding: utf-8 -*-
"""claude-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMDM8t5hoiFBKe5kLxT4Y7P25eoh3qV9
"""

!pip install yfinance pandas numpy -q
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

OSLO_BORS_AKSJER = {
      "EQNR.OL": "Equinor",
      "DNB.OL": "DNB Bank",
      "TEL.OL": "Telenor",
      "MOWI.OL": "Mowi",
      "YAR.OL": "Yara International",
      "AKRBP.OL": "Aker BP",
      "ORK.OL": "Orkla",
      "SALM.OL": "SalMar",
      "SUBC.OL": "Subsea 7",
      "NHY.OL": "Norsk Hydro",
      "BWLPG.OL": "BW LPG",
      "KOG.OL": "Kongsberg Gruppen",
      "RECSI.OL": "REC Silicon",
      "SCATC.OL": "Scatec",
      "BORR.OL": "Borr Drilling",
      "NSKOG.OL": "Norske Skog",
      "TGS.OL": "TGS",
      "STB.OL": "Storebrand",
      "GJF.OL": "Gjensidige Forsikring",
      "AUTO.OL": "AutoStore",
      "NOD.OL": "Nordic Semiconductor",
      "AKSO.OL": "Aker Solutions",
  }

def beregn_rsi(priser, perioder=14):
      delta = priser.diff()
      gevinst = delta.clip(lower=0)
      tap = -delta.clip(upper=0)
      avg_gevinst = gevinst.ewm(com=perioder - 1,
                                min_periods=perioder).mean()
      avg_tap = tap.ewm(com=perioder - 1,
                        min_periods=perioder).mean()
      rs = avg_gevinst / avg_tap
      rsi = 100 - (100 / (1 + rs))
      return round(rsi.iloc[-1], 2)

def hent_rsi_data(tickers):
      resultater = []
      for ticker, navn in tickers.items():
          try:
              data = yf.download(ticker, period="1y", progress=False,
  auto_adjust=False)
              if data.empty or len(data) < 50:
                  continue
              close = data["Close"].squeeze()
              rsi = beregn_rsi(close)
              siste_kurs = round(float(close.iloc[-1]), 2)
              resultater.append({
                  "Ticker": ticker,
                  "Navn": navn,
                  "Kurs (NOK)": siste_kurs,
                  "RSI 14": rsi
              })
          except Exception:
              pass
      return pd.DataFrame(resultater)

def skriv_ut_rapport(df):
      if df.empty:
          print("Ingen data hentet.")
          return
      df_sortert = df.sort_values("RSI 14").reset_index(drop=True)
      overkjopt = df_sortert[df_sortert["RSI 14"] > 70]
      oversolgt = df_sortert[df_sortert["RSI 14"] < 30]
      noytralt = df_sortert[(df_sortert["RSI 14"] >= 30) &
                            (df_sortert["RSI 14"] <= 70)]

      print("\nOVERSOLGT (RSI < 30) — mulig kjopssignal")
      print("-" * 65)
      if oversolgt.empty:
          print("  Ingen.")
      else:
          print(oversolgt.to_string(index=False))

      print("\nOVERKJOPT (RSI > 70) — mulig salgssignal")
      print("-" * 65)
      if overkjopt.empty:
          print("  Ingen.")
      else:
          print(overkjopt.to_string(index=False))

      print(f"\nNOYTRAL SONE (RSI 30-70) — {len(noytralt)} aksjer")
      print("-" * 65)
      print(noytralt.to_string(index=False))
      print("\n" + "=" * 65)
      print(f"  Totalt: {len(df)} | Overkjopt: {len(overkjopt)} | Oversolgt: {len(oversolgt)}")
      print("=" * 65)

df = hent_rsi_data(OSLO_BORS_AKSJER)
skriv_ut_rapport(df)

